// Generated by scripts/generate-reference-model.mjs. Do not edit.
import document0 from "../../../docs/api/import-and-setup.md?raw";
import document1 from "../../../docs/architecture/03-theming-and-styling.md?raw";
import document2 from "../../../docs/architecture/05-accessibility-standards.md?raw";
import document3 from "../../../packages/ui-data-grid/README.md?raw";
import document4 from "../../../docs/release/multi-framework-migration-and-limitations.md?raw";

export const publicDocumentMarkdownById: Readonly<Record<string, string>> =
  Object.freeze({
    "getting-started": document0,
    "theming": document1,
    "accessibility": document2,
    "data-grid": document3,
    "releases": document4,
  });
