import type { VyrnForgeCssVar } from "./theme.types";

export const vyrnForgeSemanticTokenGroups = {
  surface: [
    "--vf-surface-page",
    "--vf-surface-canvas",
    "--vf-surface-default",
    "--vf-surface-muted",
    "--vf-surface-overlay",
    "--vf-surface-sunken",
    "--vf-surface-scrim",
  ] as const,
  text: [
    "--vf-text-primary",
    "--vf-text-secondary",
    "--vf-text-tertiary",
    "--vf-text-inverse",
    "--vf-text-disabled",
    "--vf-text-link",
    "--vf-text-link-hover",
  ] as const,
  border: [
    "--vf-border-subtle",
    "--vf-border-default",
    "--vf-border-emphasis",
    "--vf-divider",
  ] as const,
  interactive: [
    "--vf-interactive-primary",
    "--vf-interactive-primary-hover",
    "--vf-interactive-primary-active",
    "--vf-interactive-primary-text",
    "--vf-interactive-selected-background",
    "--vf-interactive-selected-border",
    "--vf-interactive-selected-text",
    "--vf-interactive-neutral-hover",
    "--vf-interactive-neutral-active",
    "--vf-control-background",
    "--vf-control-background-hover",
    "--vf-control-background-active",
    "--vf-control-border",
    "--vf-control-border-hover",
    "--vf-control-disabled-background",
    "--vf-control-disabled-border",
    "--vf-control-disabled-text",
    "--vf-focus-color",
    "--vf-focus-width",
    "--vf-focus-offset",
    "--vf-focus-shadow",
  ] as const,
  status: [
    "--vf-status-success-text",
    "--vf-status-success-background",
    "--vf-status-success-border",
    "--vf-status-success-indicator",
    "--vf-status-warning-text",
    "--vf-status-warning-background",
    "--vf-status-warning-border",
    "--vf-status-warning-indicator",
    "--vf-status-error-text",
    "--vf-status-error-background",
    "--vf-status-error-border",
    "--vf-status-error-indicator",
    "--vf-status-info-text",
    "--vf-status-info-background",
    "--vf-status-info-border",
    "--vf-status-info-indicator",
    "--vf-status-pending-text",
    "--vf-status-pending-background",
    "--vf-status-pending-border",
    "--vf-status-pending-indicator",
    "--vf-status-neutral-text",
    "--vf-status-neutral-background",
    "--vf-status-neutral-border",
    "--vf-status-neutral-indicator",
  ] as const,
  density: [
    "--vf-hit-target-min",
    "--vf-control-height-sm",
    "--vf-control-height-md",
    "--vf-control-height-lg",
    "--vf-control-padding-x-sm",
    "--vf-control-padding-x-md",
    "--vf-control-padding-x-lg",
    "--vf-control-padding-y-sm",
    "--vf-control-padding-y-md",
    "--vf-control-padding-y-lg",
    "--vf-icon-size-sm",
    "--vf-icon-size-md",
    "--vf-icon-size-lg",
    "--vf-row-height-sm",
    "--vf-row-height-md",
    "--vf-row-height-lg",
    "--vf-control-height",
    "--vf-control-padding-x",
    "--vf-control-padding-y",
    "--vf-icon-size",
    "--vf-row-height",
    "--vf-component-gap",
  ] as const,
  typography: [
    "--vf-type-display-font-family",
    "--vf-type-display-font-size",
    "--vf-type-display-font-weight",
    "--vf-type-display-line-height",
    "--vf-type-display-letter-spacing",
    "--vf-type-page-title-font-family",
    "--vf-type-page-title-font-size",
    "--vf-type-page-title-font-weight",
    "--vf-type-page-title-line-height",
    "--vf-type-page-title-letter-spacing",
    "--vf-type-section-title-font-family",
    "--vf-type-section-title-font-size",
    "--vf-type-section-title-font-weight",
    "--vf-type-section-title-line-height",
    "--vf-type-section-title-letter-spacing",
    "--vf-type-label-font-family",
    "--vf-type-label-font-size",
    "--vf-type-label-font-weight",
    "--vf-type-label-line-height",
    "--vf-type-label-letter-spacing",
    "--vf-type-body-font-family",
    "--vf-type-body-font-size",
    "--vf-type-body-font-weight",
    "--vf-type-body-line-height",
    "--vf-type-body-letter-spacing",
    "--vf-type-caption-font-family",
    "--vf-type-caption-font-size",
    "--vf-type-caption-font-weight",
    "--vf-type-caption-line-height",
    "--vf-type-caption-letter-spacing",
    "--vf-type-code-font-family",
    "--vf-type-code-font-size",
    "--vf-type-code-font-weight",
    "--vf-type-code-line-height",
    "--vf-type-code-letter-spacing",
    "--vf-type-numeric-font-family",
    "--vf-type-numeric-font-size",
    "--vf-type-numeric-font-weight",
    "--vf-type-numeric-line-height",
    "--vf-type-numeric-letter-spacing",
  ] as const,
  motion: [
    "--vf-motion-duration-instant",
    "--vf-motion-duration-fast",
    "--vf-motion-duration-standard",
    "--vf-motion-duration-slow",
    "--vf-motion-duration-deliberate",
    "--vf-motion-easing-standard",
    "--vf-motion-easing-enter",
    "--vf-motion-easing-exit",
    "--vf-motion-easing-emphasized",
    "--vf-motion-transition-color",
    "--vf-motion-transition-opacity",
    "--vf-motion-transition-transform",
  ] as const,
  layer: [
    "--vf-layer-base",
    "--vf-layer-raised",
    "--vf-layer-sticky",
    "--vf-layer-dropdown",
    "--vf-layer-popover",
    "--vf-layer-tooltip",
    "--vf-layer-scrim",
    "--vf-layer-modal",
    "--vf-layer-toast",
    "--vf-layer-debug",
  ] as const,
} as const satisfies Record<string, readonly VyrnForgeCssVar[]>;

export const vyrnForgeCanonicalDensities = [
  "compact",
  "balanced",
  "spacious",
] as const;

export const vyrnForgeDensityAliases = {
  standard: "balanced",
  comfortable: "spacious",
} as const;

export const vyrnForgeLayerOrder = [
  { name: "--vf-layer-base", level: 0 },
  { name: "--vf-layer-raised", level: 10 },
  { name: "--vf-layer-sticky", level: 20 },
  { name: "--vf-layer-dropdown", level: 40 },
  { name: "--vf-layer-popover", level: 50 },
  { name: "--vf-layer-tooltip", level: 60 },
  { name: "--vf-layer-scrim", level: 70 },
  { name: "--vf-layer-modal", level: 80 },
  { name: "--vf-layer-toast", level: 90 },
  { name: "--vf-layer-debug", level: 9999 },
] as const;

export const vyrnForgeThemeColorTokens = [
  "--vf-surface-page",
  "--vf-surface-canvas",
  "--vf-surface-default",
  "--vf-surface-muted",
  "--vf-surface-overlay",
  "--vf-surface-sunken",
  "--vf-surface-scrim",
  "--vf-text-primary",
  "--vf-text-secondary",
  "--vf-text-tertiary",
  "--vf-text-inverse",
  "--vf-text-disabled",
  "--vf-text-link",
  "--vf-text-link-hover",
  "--vf-border-subtle",
  "--vf-border-default",
  "--vf-border-emphasis",
  "--vf-divider",
  "--vf-interactive-primary",
  "--vf-interactive-primary-hover",
  "--vf-interactive-primary-active",
  "--vf-interactive-primary-text",
  "--vf-interactive-selected-background",
  "--vf-interactive-selected-border",
  "--vf-interactive-selected-text",
  "--vf-interactive-neutral-hover",
  "--vf-interactive-neutral-active",
  "--vf-control-background",
  "--vf-control-background-hover",
  "--vf-control-background-active",
  "--vf-control-border",
  "--vf-control-border-hover",
  "--vf-control-disabled-background",
  "--vf-control-disabled-border",
  "--vf-control-disabled-text",
  "--vf-focus-color",
  "--vf-status-success-text",
  "--vf-status-success-background",
  "--vf-status-success-border",
  "--vf-status-success-indicator",
  "--vf-status-warning-text",
  "--vf-status-warning-background",
  "--vf-status-warning-border",
  "--vf-status-warning-indicator",
  "--vf-status-error-text",
  "--vf-status-error-background",
  "--vf-status-error-border",
  "--vf-status-error-indicator",
  "--vf-status-info-text",
  "--vf-status-info-background",
  "--vf-status-info-border",
  "--vf-status-info-indicator",
  "--vf-status-pending-text",
  "--vf-status-pending-background",
  "--vf-status-pending-border",
  "--vf-status-pending-indicator",
  "--vf-status-neutral-text",
  "--vf-status-neutral-background",
  "--vf-status-neutral-border",
  "--vf-status-neutral-indicator",
] as const satisfies readonly VyrnForgeCssVar[];

export type VyrnForgeSemanticTokenGroup =
  keyof typeof vyrnForgeSemanticTokenGroups;

export type VyrnForgeSemanticToken =
  (typeof vyrnForgeSemanticTokenGroups)[VyrnForgeSemanticTokenGroup][number];

export type VyrnForgeCanonicalDensity =
  (typeof vyrnForgeCanonicalDensities)[number];

export type VyrnForgeLayerToken = (typeof vyrnForgeLayerOrder)[number]["name"];
