import type { CSSProperties } from "react";

export type DataGridCssVar =
  | "--udg-font-family"
  | "--udg-font-size"
  | "--udg-font-size-xs"
  | "--udg-font-size-sm"
  | "--udg-font-size-md"
  | "--udg-font-size-lg"
  | "--udg-font-weight-normal"
  | "--udg-font-weight-medium"
  | "--udg-font-weight-semibold"
  | "--udg-space-1"
  | "--udg-space-2"
  | "--udg-space-3"
  | "--udg-space-4"
  | "--udg-space-5"
  | "--udg-radius"
  | "--udg-radius-sm"
  | "--udg-radius-md"
  | "--udg-radius-lg"
  | "--udg-shadow"
  | "--udg-shadow-sm"
  | "--udg-shadow-md"
  | "--udg-bg"
  | "--udg-surface"
  | "--udg-surface-subtle"
  | "--udg-surface-ra-sm"
  | "--udg-surface-muted"
  | "--udg-popover-bg"
  | "--udg-toolbar-bg"
  | "--udg-text"
  | "--udg-text-muted"
  | "--udg-text-strong"
  | "--udg-border"
  | "--udg-border-strong"
  | "--udg-primary"
  | "--udg-primary-hover"
  | "--udg-primary-soft"
  | "--udg-danger"
  | "--udg-danger-soft"
  | "--udg-warning"
  | "--udg-warning-soft"
  | "--udg-success"
  | "--udg-success-soft"
  | "--udg-info"
  | "--udg-info-soft"
  | "--udg-focus-ring"
  | "--udg-toolbar-height"
  | "--udg-header-height"
  | "--udg-row-height"
  | "--udg-cell-padding-x"
  | "--udg-cell-padding-y"
  | "--udg-control-height"
  | "--udg-control-bg"
  | "--udg-control-border"
  | "--udg-control-hover-border"
  | "--udg-control-disabled-bg"
  | "--udg-control-disabled-text"
  | "--udg-control-focus"
  | "--udg-control-focus-border"
  | "--udg-header-bg"
  | "--udg-header-text"
  | "--udg-row-bg"
  | "--udg-row-hover-bg"
  | "--udg-row-selected-bg"
  | "--udg-row-border"
  | "--udg-skeleton-base"
  | "--udg-skeleton-highlight";

export type DataGridThemeVars = Partial<Record<DataGridCssVar, string>>;

export type DataGridThemePreset = {
  name: string;
  vars: DataGridThemeVars;
};

export type DataGridThemeStyle = CSSProperties & Record<string, string>;
